[package]
name = "treemerge"
version = "0.0.3"
edition = "2024"

[dependencies]
walkdir = "2"
clap = { version = "4", features = ["derive"] }
globset = "0.4"
anyhow = "1"
infer = "0.19"
rayon = "1.10"
indicatif = "0.18.3"
